"""
Django settings for gconfs_website project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*os(t$y12dob(=_5fhee+28c9#jhat#vbmfsdij6+n47=9-tij'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'homepage',
        'confs',
        'team',
        'statuts',
        'contact',
        'stream',
        'captcha',
        'records',
        )

MIDDLEWARE_CLASSES = (
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
        'django.middleware.security.SecurityMiddleware',
        )

ROOT_URLCONF = 'gconfs_website.urls'

TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [os.path.join(BASE_DIR, 'templates')],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                    ],
                },
            },
        ]

WSGI_APPLICATION = 'gconfs_website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'gconfs-website-db',
            'USER': 'gconfs-db-admin',
            'PASSWORD': 'gconfs-db-password',
            'HOST': '127.0.0.1',
            'PORT': '5432',
            }
        }


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATICFILES_DIRS = (
        os.path.join(BASE_DIR, "static"),
        )

STATIC_URL = '/static/'


# Media settings : user-uploaded files
# E.g. : confs posters

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# URLs settings
APPEND_SLASH = True
PREPEND_WWW = False

from .captcha import *

try:
    from .smtp import *
except:
    EMAIL_HOST = '' # TODO: e.g gmail.com
    EMAIL_HOST_USER = '' # TODO: e.g test@example.com
    EMAIL_HOST_PASSWORD = '' # TODO: mysecurepassword
    EMAIL_PORT = 4242 # TODO: e.g 4242
    EMAIL_SUBJECT_PREFIX = '[GCONFS][CONTACT] '
    EMAIL_USE_TLS = True
    CONTACT_EMAIL = '' # TODO: e.g test@example.com
    CR_EMAIL = '' # TODO: e.g test@example.com
    CR_MESSAGE_START = ('Bonjour,\n\nSuite à la réunion du {}, en voici le'
            'compte rendu :\n\n')
    CR_MESSAGE_END = '\n\nCR-ment,\n\n-- \nVotre dévoué site web'
    EMAIL_STD_PREFIX = '[GCONFS][1516]'
